name = "my-astro-app"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-08-24"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true